table Fact_Sales
	lineageTag: 43a676d4-fde3-4fbe-b697-2b2dc9e8ccde

	measure 'Total Sales' = SUM(Fact_Sales[sales_amount])
		lineageTag: 2fa79a41-cc16-4b26-8846-c81c97e6ead0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Month Sales' =
			
			CALCULATE(
			    [Total Sales],
			    DATEADD(Dim_Date[date], -1, MONTH)
			)
		lineageTag: a67a9036-0c68-4d21-9902-b3f5ba4a2786

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			DIVIDE(
			    [Total Sales] - [Previous Month Sales],
			    [Previous Month Sales],
			    0
			)
		lineageTag: ddaccbb8-3dac-4b2a-99ca-53e4f5b8f609

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALLSELECTED(Dim_Date[date]),
			        Dim_Date[date] <= MAX(Dim_Date[date])
			    )
			)
		lineageTag: 5396f5f3-5a63-4ed0-86f3-ce51cc3e5c20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 1bc2b58a-99e8-4b63-9a69-73561502ffeb
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 193d6ceb-e9da-4aa8-ae66-51d989f24eba
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 912bbbb0-2a59-4930-9738-8633b317e52b
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: df64cfc4-0745-41d7-9f58-9cea7e80ee5d
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: c7f028f0-1ccf-4df3-a514-839593fb3ae8
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: bcdfddfd-7a38-4a67-a0f4-c4b46341ef7b
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: da41f66c-97d1-4243-9980-5637429fafdd
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: ae2ba284-bf27-498e-aeed-67d3581ce7a8
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 29ce86e9-5cab-4573-8e5b-6424f3a321e3
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\THANGA ANGEL M\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

